name: cd

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "importer-commit-graph"
      - "importer-treemap"
    types:
      - completed

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn

      - name: Fetch community map SVGs
        run: |
          cd static/community-map
          git clone --depth=1 -b community-map https://github.com/ArthurSonzogni/ChromeCommitTracker.git
          cd ChromeCommitTracker
          cp *.svg ..
          cd ..
          rm -rf ChromeCommitTracker

      - name: Generate
        run: yarn generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
