name: cd

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "importer-graph"
      - "importer-treemap"
    types:
      - completed

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build website
        run: |
          yarn
          yarn pull-data
          yarn generate-derived-data
          yarn generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true
