name: importer-treemap

on:
  schedule:
    - cron:  '0 0 * * 3' # every week on Thursday.
  workflow_dispatch:

jobs:
  importer-treemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Pull data
        run: |
          yarn
          yarn pull-data

      - name: Refresh files
        run: |
          cd importer
          npm install
          npm run treemap
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add static/data
          git commit -m 'refresh treemap data'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
