name: importer-treemap

on:
  schedule:
    - cron:  '0 0 * * 3' # every week on Thursday.
  workflow_dispatch:

jobs:
  importer-treemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: Refresh files
        run: |
          cd importer
          git clone --depth=1 https://github.com/chromium/chromium
          npm install
          npm run treemap
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add static/data
          git commit -m 'refresh treemap data'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
