name: importer-commit-timeline

on:
  schedule:
    - cron:  '0 0 * * 0' # every week
  push:
  workflow_dispatch:

jobs:
  importer-commit-timeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          repository: ArthurSonzogni/ChromeCommitTracker
          ref: main

      - name: Remove data and community-map
        run: |
          cd static
          rm -rf data
          rm -rf community_map

      - name: Checkout data
        uses: actions/checkout@v4
        with:
          repository: ArthurSonzogni/ChromeCommitTracker
          ref: data
          path: static/data

      - name: Checkout community-map
        uses: actions/checkout@v4
        with:
          repository: ArthurSonzogni/ChromeCommitTracker
          ref: community-map
          path: static/community-map

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Refresh files
        run: |
          cd importer
          npm install
          npm run main
          npm run users_info
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push data
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./static/data/
          publish_branch: data
          force_orphan: true
