name: importer-commit-timeline

on:
  schedule:
    - cron:  '0 0 * * 0' # every week
  push:
  workflow_dispatch:

jobs:
  importer-commit-timeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Refresh files
        run: |
          cd importer
          npm install
          npm run main
          npm run users_info
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push data
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./static/data/
          publish_branch: data
